# Generated by Django 2.2.9 on 2020-02-03 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_featured'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='aauthor',
            new_name='author',
        ),
    ]
