# Generated by Django 2.2.9 on 2020-03-11 14:55

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('flatpages', '0001_initial'),
        ('posts', '0007_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewFlatPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', tinymce.models.HTMLField()),
                ('text_block', tinymce.models.HTMLField()),
                ('flatpage', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='flatpages.FlatPage')),
            ],
        ),
    ]
